### ISSUE TITLE
Minimap doesn't resize properly after splitting

### ISSUE THREAD

**Issue by GameplayJDK** [fundon/atom-minimap#190]
After `Right Click on Editor > Split *` the minimap is only resized for one pane:
![issue02](https://cloud.githubusercontent.com/assets/4069263/5587367/53bfea20-909d-11e4-985f-c37fb37dd3bd.png)
(Atom v0.165.0; Windows 8.1, Ubuntu 14.04 Unity)

**Comment by abe33** [comment]
I thought most resize issues was fixed in latest version by listening to panes creation/destruction and resize all minimap in that situation. It seems there's some race conditions that will be hard to track efficiently (event triggered before the DOM was actually modified).

I'm working on v4 that will use the same DOM polling approach that atom text editors to resize themselves, so far I haven't got much issues when splitting panes. I'll plan to publish 3.5.0 with a setting to enable a preview of v4 to allow people to test if these kind of bug still occurs.

**Comment by abe33** [comment]
I just published v3.5.0 if you to give it a try, I still have some issues with the width of the minimap in flex box as webkit has some weird way to handle percentage in that layout but the problem of stretching/measurements should be fixed when `V4 preview` setting is enabled.

**Comment by GameplayJDK** [comment]
I'll give it a try for sure! :smiley:

**Comment by abe33** [comment]
Fixed with v4.
