### ISSUE TITLE
Dragging off the minimap immediately stops scrolling

### ISSUE THREAD

**Issue by 1j01** [fundon/atom-minimap#191]
It should keep scrolling until you release the mouse.
It'd also be nice if you could continue dragging after clicking on a location outside the viewport.

**Comment by abe33** [comment]
I'm not sure I correctly understand your report: 

1. Do you mean than starting a dragging gesture from the minimap visible area and then moving the mouse outside the minimap should continue to drag the minimap visible area? 
2. Do you mean than pressing the mouse over a part of the minimap (not the visible area) should start a dragging gesture?

Point 1 will be fixed in v4, and could be fixed easily in v3 (v4 implementation can be use as base for the changes in v3).
Point 2 is not really realistic as clicking on minimap track is used to scroll to the corresponding line in the file, which will appear at a different location once the minimap have updated its own scroll (in the case the minimap can scroll).

I'll gladly accept any PR for point 1 if you think you can do it, as I already have quite a lot of work with v4 and the changes in the new version will also mean a rewrite of important parts in all the plugins.

**Comment by 1j01** [comment]
Yes, those are what I mean. I don't think the second thing is as important as the first but I think Sublime does both, and it's kinda nice. When you drag the view normally with the minimap the lines go to different positions as well, so it should work with the same mechanism. That should be a separate issue though. Primarily I want to be able to scroll off of the minimap. Even if you try to scroll to the bottom really fast it'll stop if you go onto the status bar...
I forked but have not had any success.

**Comment by abe33** [comment]
Closing as point 1 was fixed with v4 and point 2 don't really make sens as I explained.

**Comment by 1j01** [comment]
Ah, this is very nice! And I remembered incorrectly: Sublime Text just animates the jump-to scrolling, it doesn't let you start a drag from a jump
